name: k_chart_pw
description: A Flutter K Chart. On the basis of the forked, we added the function that will show buy sell signal on the charts
version: 0.5.1
homepage: https://github.com/pecpwee/k_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
